/**
 * *
 * This file has been automatically generated by XText and is part of the source code of the
 * GAMA modeling and simulation platform (v.2.0.0).
 * 
 * (c) 2007-2021 UMI 209 UMMISCO IRD/SU & Partners (IRIT, MIAT, TLU, CTU)
 * 
 * Visit https://github.com/gama-platform/gama for license information and contacts.
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getActionFakeDefinition()
 * @model
 * @generated
 */
public interface ActionFakeDefinition extends ActionDefinition
{
} // ActionFakeDefinition
