/**
 * *
 * This file has been automatically generated by XText and is part of the source code of the
 * GAMA modeling and simulation platform (v.2.0.0).
 * 
 * (c) 2007-2021 UMI 209 UMMISCO IRD/SU & Partners (IRIT, MIAT, TLU, CTU)
 * 
 * Visit https://github.com/gama-platform/gama for license information and contacts.
 */
package gama.core.lang.gaml.impl;

import gama.core.lang.gaml.GamlPackage;
import gama.core.lang.gaml.S_Action;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SAction</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_ActionImpl extends S_DefinitionImpl implements S_Action
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_ActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SACTION;
  }

} //S_ActionImpl
